# Generated by Django 4.2 on 2023-04-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0002_cart"),
    ]

    operations = [
        migrations.RemoveField(model_name="cart", name="unit_price",),
    ]
