# Generated by Django 4.2 on 2023-04-22 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0004_order_alter_cart_menu_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    2023, 4, 22, 22, 32, 27, 848885, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
